service: phonebook-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-north-1
  profile: sls
  stage: dev
  environment:
    DYNAMODB_TABLE: ${self:service}-${sls:stage}
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 'dynamodb:PutItem'
            - 'dynamodb:Get*'
            - 'dynamodb:Scan*'
            - 'dynamodb:UpdateItem'
            - 'dynamodb:DeleteItem'
          Resource: arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${self:provider.environment.DYNAMODB_TABLE}"
	
resources:
  Resources:
    CustomerTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        TableName: ${self:service}-${sls:stage}

functions:  	
  createPerson:
    handler: handlers/createPerson.createPerson
    events:
      - httpApi:
          path: /persons
          method: post
  getPeople:
    handler: handlers/getPeople.getPeople
    events:
      - httpApi:
          path: /persons
          method: get
  getPerson:
    handler: handlers/getPerson.getPerson
    events:
      - httpApi:
          path: /persons/{id}
          method: get

